import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
enum Locale {
  AZ = "az",
  EN = "en",
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale?: string };
}) {
  // Locale yoxlaması
  const locale = (await params)?.locale;

  if (!locale || !routing.locales.includes(locale as Locale)) {
    notFound();
  }

  // Mesajların alınması
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages} >
          <div className='flex flex-col '>
            <Header />
            <div className='flex-grow mt-20'>{children}</div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
